on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  chatgptComment:
    runs-on: ubuntu-latest
    name: Autgenerate Comment
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Autgenerate Comment
        uses: ./
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          open-api-key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          model: ${{ secrets.AZURE_OPENAI_MODEL }}
          endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          max-prompt-tokens: '50000'
          ignore-paths: 'dist, .gitignore, package.json, package-lock.json, README.md, .husky, .github'
